---
- hosts: web_nodes
  become: true
  tasks:
    - name: Copying a file to all hosts
      copy:
        src: /usr/share/nginx/html/file.txt
        dest: /usr/share/nginx/html/file-copy.txt
        remote_src: yes