---
- hosts: web_node1
  become: yes
  tasks:
    - name: Insert a line into a file
      ansible.builtin.lineinfile:
        path: /usr/share/nginx/html/file.txt
        line: 'This line is inserted by Ansible'
        insertbefore: BOF