---
- hosts: web_node1
  become: true
  tasks:
    - name: Replace text in file
      ansible.builtin.replace:
        path: /usr/share/nginx/html/file.txt
        regexp: 'KT'
        replace: 'Myo Min S'

- hosts: web_node2
  become: true
  tasks:
    - name: replace text in file
      ansible.builtin.replace:
        path: /usr/share/nginx/html/file.txt
        regexp: 'KT'
        replace: 'DevOps'
