---
- hosts: web_node1
  become: true
  tasks:
    - name: Create file using a template
      ansible.builtin.template:
        src: templates/hello.txt.j2
        dest: /usr/share/nginx/html/hello.txt
